Creación de archivos index.html, application.scss, .gitignore
wolox-training/jg-react-native pull request #1
Opened 2018-10-30 18:20 UTC by jeymarsonwolox

Ejercicio de Setup del proyecto.

2018-10-30 19:47 UTC, FrankIglesias requested changes
add empty line at the bottom of the file

2018-10-30 19:47 UTC, FrankIglesias commented on scss/styles.scss
> +.title {
check indentation

2018-10-30 20:20 UTC, jeymarsonwolox commented
Correction in file indentation

2018-10-30 23:14 UTC, FrankIglesias requested changes
Just one fix and go

2018-10-30 23:14 UTC, FrankIglesias commented on .gitignore
> +.DS_Store
add empty line to the gitignore

2018-10-31 15:42 UTC, jeymarsonwolox commented
Empty line is added to gitignore

2018-10-31 18:11 UTC, FrankIglesias approved these changes

2018-11-01 15:01 UTC, merged