Final implementation
wolox-training/jg-react-native pull request #10
Opened 2018-12-04 14:38 UTC by jeymarsonwolox

Summary

- Session persistence.
- Redirection according to the session

Screenshot

<img width="396" alt="captura de pantalla 2018-12-03 a la s 9 14 51 a m" src="https://user-images.githubusercontent.com/44580968/49449149-480a4880-f7a8-11e8-836a-f9e9faa14c7e.png">

Trello card

https://trello.com/c/zdCcKqYt

2018-12-05 03:24 UTC, julibel requested changes
Nice!

2018-12-05 03:24 UTC, julibel commented on tic-tac-toe/src/app/index.js
> +  constructor(props) {
`constructor` shouldn't be needed.. what are you using it for?

2018-12-05 03:24 UTC, julibel commented on tic-tac-toe/src/app/index.js
> +  history: PropTypes.shape({})
same as the other PR.. you should complete the shape with every field inside the object..

2018-12-05 03:24 UTC, julibel commented on tic-tac-toe/src/app/screens/Game/index.js
> +    if (loggedState !== LOGGEDIN) {
idem, don't use constructor! let's check this tomorrow to see another options 😉

2018-12-05 03:24 UTC, julibel commented on tic-tac-toe/src/app/screens/Login/components/ModalError/index.js
> +    this.props.dispatch(actionsLogin.change(OUT));
from this line, it could be interpreted that every time you close the modal you dispatch an action.. i don't think that's really needed.. can you tell me a bit more of this action?

2018-12-05 03:24 UTC, julibel commented on tic-tac-toe/src/app/screens/Login/index.js
> +    if (loggedState === LOGGEDIN) {
same as before. we will talk about it tomorrow

2018-12-05 03:24 UTC, julibel commented on tic-tac-toe/src/app/screens/Login/layout.js
> +          name="username"
as i marked in other PR, let's separate the field's name in another file

2018-12-05 03:24 UTC, julibel commented on tic-tac-toe/src/config/header.js
> +  if (token) {
use a ternary here

2018-12-05 03:24 UTC, julibel commented on tic-tac-toe/src/config/session.js
> +  dispatch(loginActions.change(state));
i think i would make more specific actions.. in particular in the login case, i think it would be better to have an AUTH_SUCCESS anda a AUTH_FAILURE disparched.

2018-12-05 03:24 UTC, julibel commented on tic-tac-toe/src/redux/Login/actions.js
> +
delete empty line

2018-12-05 03:24 UTC, julibel commented on tic-tac-toe/src/redux/Login/actions.js
> +      dispatch({ type: actions.AUTH });
ask me for this tomorrow! so we can see other options..

2018-12-06 15:52 UTC, jeymarsonwolox commented
- Session validation
- Modal behavior

2018-12-07 03:54 UTC, julibel requested changes
Nice! Just a comments..

2018-12-07 03:54 UTC, julibel commented on tic-tac-toe/src/app/index.js
> +  state = {};
are you using this?

2018-12-07 03:54 UTC, julibel commented on tic-tac-toe/src/redux/Login/actions.js
> +  change: state => ({ type: state ? actions.LOGIN_SUCCESS : actions.LOGIN_FAILURE })
try not to use the same action for 2 diferent methods.. do you really need change action?

2018-12-07 03:54 UTC, julibel commented on tic-tac-toe/src/redux/Login/reducer.js
>  const reducer = (state = initialState, action) => {
Excellent reducer! check that you are not using CHANGE action in this.. that's a clear clue that you don't really need it for this flow. What do you think?

2018-12-07 03:56 UTC, julibel commented
@jeymarsonwolox mark as 'resolved' the comments that you have already correct or that you have done it in other PR.. just `Reply` to give info in each comment

2018-12-07 17:02 UTC, julibel approved these changes

2018-12-07 21:13 UTC, merged