Topbar
wolox-training/jg-react-native pull request #11
Opened 2018-12-04 16:16 UTC by jeymarsonwolox

Summary

Top Bar implementation

Screenshot

<img width="538" alt="captura de pantalla 2018-12-04 a la s 11 16 00 a m" src="https://user-images.githubusercontent.com/44580968/49455934-08e2f400-f7b6-11e8-9345-e10f905d50a5.png">

Trello card

https://trello.com/c/Eck6yoWy

2018-12-05 03:31 UTC, julibel requested changes
I marked some issues here and others.. are in other PRs 👼

2018-12-05 03:31 UTC, julibel commented on tic-tac-toe/src/app/components/Topbar/layout.js
> +    console.log(this.props);
delete this console.log

2018-12-05 03:31 UTC, julibel commented on tic-tac-toe/src/app/index.js
> +    sessionValidation(props.dispatch);
as i marked in another PR.. we should not be using constructor. We will talk about it tomorrow

2018-12-05 03:31 UTC, julibel commented on tic-tac-toe/src/app/index.js
> +  history: PropTypes.shape({}),
idem other PRs, lets comeplete the shape

2018-12-05 03:31 UTC, julibel commented on tic-tac-toe/src/app/screens/Game/index.js
> +    const { loggedState } = props;
idem

2018-12-06 16:05 UTC, jeymarsonwolox commented
Change session validation

2018-12-07 03:57 UTC, julibel requested changes
Perfect!! Just a comment..

2018-12-07 03:57 UTC, julibel commented on tic-tac-toe/src/app/components/Topbar/layout.js
> +  ),
is requiered?

2018-12-07 03:59 UTC, julibel commented on tic-tac-toe/src/app/components/Topbar/layout.js
> +  ),
i seen it in other PR!! done.. this is good to go. Be careful with the merge 👀

2018-12-07 04:01 UTC, julibel approved these changes
Be careful when you merge! take into account that this is going to the other branch.. so i would correct all of them first, and when everything is approve, it can be merged in order. Just an idea.. feel free with this 😉

2018-12-07 21:13 UTC, merged