Creation of content layout, footer and navbar of the page
wolox-training/jg-react-native pull request #2
Opened 2018-11-01 16:04 UTC by jeymarsonwolox

**Summary**
Add items specified in the cards with their respective scss.

**Screenshots**
![cap-001](https://user-images.githubusercontent.com/44580968/47863498-6bb32b00-ddc5-11e8-810e-e75636c627be.png)
![cap-002](https://user-images.githubusercontent.com/44580968/47863499-6bb32b00-ddc5-11e8-8627-f14c869508cf.png)

**Trello Card**
https://trello.com/c/BRjY95n0/11-setup-del-proyecto

2018-11-01 18:26 UTC, FrankIglesias requested changes

2018-11-01 18:26 UTC, FrankIglesias commented on index.html
> +      <img src="assets/triangle.svg" alt="Front-End Tools" class="img-title">
You can change this to a pseudo element

2018-11-01 18:26 UTC, FrankIglesias commented on index.html
> +      <h4 class="text-title">Front-End Tools</h4>
change this for an h2

2018-11-01 18:26 UTC, FrankIglesias commented on index.html
> +        <div class="tech-back"></div>
this can be a pseudo element

2018-11-01 18:26 UTC, FrankIglesias commented on index.html
> +    <div class="div-cont-tech">
and by doing that you can remove this

2018-11-01 18:26 UTC, FrankIglesias commented on index.html
> +      <div class="div-tech">
use another name for this class

2018-11-01 18:26 UTC, FrankIglesias commented on index.html
> +          <img src="assets/react_icon.svg" alt="ReactJS" class="img-tech">
add a slash before >

2018-11-01 18:26 UTC, FrankIglesias commented on index.html
> +            <p class="tech-title">ReactJS</p>
use a more important tag like h3 or h4

2018-11-01 18:26 UTC, FrankIglesias commented on index.html
> +            <br>
delete this

2018-11-01 18:26 UTC, FrankIglesias commented on index.html
> +          <div class="div-info-tech">
delete this

2018-11-01 18:26 UTC, FrankIglesias commented on index.html
> +      <div class="div-tech">
Do the same for all techs

2018-11-01 18:26 UTC, FrankIglesias commented on index.html
> +  <div class="footer">
use a footer here

2018-11-01 18:26 UTC, FrankIglesias commented on index.html
> +    <div class="div-title">
delete this div

2018-11-01 18:26 UTC, FrankIglesias commented on index.html
> +  <div class="nav">
use a nav tag

2018-11-01 18:26 UTC, FrankIglesias commented on index.html
> +
delete this line

2018-11-01 18:26 UTC, FrankIglesias commented on scss/footer.scss
> +$text-color: white;
move this to colors

2018-11-01 18:26 UTC, FrankIglesias commented on scss/navbar.scss
> +  background-color: white;
add a color varaible

2018-11-01 18:26 UTC, FrankIglesias commented on scss/navbar.scss
> +  top: 0;
add a left prop

2018-11-01 18:26 UTC, FrankIglesias commented on scss/tech.scss
> +.div-tech:hover > .tech-back {
nest this rule inside the .div-tech class

2018-11-01 18:26 UTC, FrankIglesias commented on scss/titles.scss
> +  right: 18px;
why this right and top?

2018-11-02 14:20 UTC, jeymarsonwolox commented
Corrections are made to annotations of the pull request.

2018-11-02 21:57 UTC, FrankIglesias requested changes

2018-11-02 21:57 UTC, FrankIglesias commented on scss/titles.scss
> +.title::before {
You can nest this pseudo element inside the title class

2018-11-02 21:57 UTC, FrankIglesias commented on index.html
> +    <div class="tech">
delete this div and ony use one div

2018-11-02 21:57 UTC, FrankIglesias commented on scss/tech.scss
> +  right: ($width - 8);
8px

2018-11-06 16:08 UTC, jeymarsonwolox commented
Corrections are made to annotations of the pull request.

2018-11-06 16:34 UTC, FrankIglesias requested changes

2018-11-06 16:34 UTC, FrankIglesias commented on scss/footer.scss
> +  padding: 45px 25px 15px 25px;
`padding: 45px 25px 15px;`

2018-11-06 16:39 UTC, jeymarsonwolox commented
Correction in padding footer

2018-11-07 00:22 UTC, FrankIglesias requested changes
One comment

2018-11-07 00:22 UTC, FrankIglesias commented on index.html
> +  <nav class="nav">
I think the wolox logo is missing

2018-11-07 14:11 UTC, jeymarsonwolox commented
Change wolox logo to img

2018-11-07 14:15 UTC, FrankIglesias approved these changes

2018-11-07 14:16 UTC, merged