Design with CSS Grid
wolox-training/jg-react-native pull request #3
Opened 2018-11-02 20:05 UTC by jeymarsonwolox

Summary
Change of design to css grid

Screenshots
<img width="1297" alt="captura de pantalla 2018-11-02 a la s 3 00 59 p m" src="https://user-images.githubusercontent.com/44580968/47937919-5ff06300-deb0-11e8-9714-872856119ea3.png">
<img width="1298" alt="captura de pantalla 2018-11-02 a la s 3 01 22 p m" src="https://user-images.githubusercontent.com/44580968/47937927-654dad80-deb0-11e8-94c7-0ee6a9796856.png">
<img width="1290" alt="captura de pantalla 2018-11-02 a la s 3 01 34 p m" src="https://user-images.githubusercontent.com/44580968/47937932-68e13480-deb0-11e8-8f9b-f711763943fc.png">

Trello Card
https://trello.com/c/KOZDpaqq/12-redise%C3%B1o-de-la-p%C3%A1gina

2018-11-02 21:59 UTC, FrankIglesias approved these changes

2018-11-02 21:59 UTC, FrankIglesias commented on index.html
> +
delete this lines

2018-11-02 21:59 UTC, FrankIglesias commented on index.html
> +
same

2018-11-02 21:59 UTC, FrankIglesias commented on index.html
> +    <div class="tech tech-fr tech-pr">
why this suffixes?

2018-11-02 21:59 UTC, FrankIglesias requested changes
Check the comments

2018-11-06 17:43 UTC, jeymarsonwolox commented
Corrections are made to annotations of the pull request.

2018-11-08 01:16 UTC, FrankIglesias requested changes

2018-11-08 01:16 UTC, FrankIglesias commented on scss/tech.scss
> +  padding: 50% 10% 50% 0;
use px instead for this props

2018-11-13 14:06 UTC, jeymarsonwolox commented
Correction of props to px

2018-11-13 21:54 UTC, FrankIglesias approved these changes

2018-11-13 22:25 UTC, merged