Apply redux to project
wolox-training/jg-react-native pull request #6
Opened 2018-11-20 18:19 UTC by jeymarsonwolox

**Summary**
Changes aplication state to use with redux

**Screenshots**
<img width="319" alt="captura de pantalla 2018-11-15 a la s 4 38 50 p m" src="https://user-images.githubusercontent.com/44580968/48793989-acb4a600-ecc6-11e8-81be-b74f85211e93.png">

**Trello card**
https://trello.com/c/ntCIt7qR

2018-11-21 02:48 UTC, julibel requested changes
Great work! I marked a few things.. most of them are about re organizing the files and folder. That's because we have some conventions in wolox and i would like you to use it as we where in a real project 😄

2018-11-21 02:48 UTC, julibel commented on tic-tac-toe/src/app/components/game/index.js
> +          <Board squares={current.squares} onClick={i => this.props.dispatch(clickSquare(i))} />
lets extract this function.. you should have something here like: this.handleClick(i).. we will keep improving this later 😉

2018-11-21 02:48 UTC, julibel commented on tic-tac-toe/src/app/reducers/index.js
> +const reducer = (state = initialState, action) => {
okey, as we talk.. we should only have in the reducer a single function per action, and each has to have nothing more than the update to the store/state. The rest of the function should be in the class

2018-11-21 02:48 UTC, julibel commented on tic-tac-toe/src/index.js
>  import Game from './app/components/game';
before continuing with this, let's make a refactor of the files.. until now, you have a 'component' folder with everything inside. We should separete it in two: components and screens. The components are those you will repeat in more than one screen (for example a button or a modal). The screens corresponds directly with the screen you have in the app. So, i think Game it's the screen that includes other components. In case a screen has some code repeated that should be extract to a component but no other screen will use it, we include a 'component' folder inside the screen folder
Like this:
<img width="286" alt="screen shot 2018-11-20 at 17 25 36" src="https://user-images.githubusercontent.com/5510533/48809213-54db6680-ece9-11e8-9659-6ae69d9200d4.png">
So try to redo the src/components using this idea! anything it's not clear, ask me! 😉

2018-11-21 02:48 UTC, julibel commented on tic-tac-toe/src/index.js
> +const store = createStore(reducer);
create a redux folder at the same level of app (inside of src) and there add folder with a name that's descriptive to the actions that will be there. For example: game, moves.. Then add files: actions.js and reducer.js (with the code you have already done). Also, inside de 'redux' folder you should have a file call 'store.js'. There you should have this line, that creates the store.. and everything related, for example middlewares. 
It should be like this:
<img width="181" alt="screen shot 2018-11-20 at 17 38 25" src="https://user-images.githubusercontent.com/5510533/48809658-1e065000-eceb-11e8-9c51-0e0f26cb57fb.png">

2018-11-21 02:48 UTC, julibel commented on tic-tac-toe/src/app/components/game/index.js
> +  history: state.history,
state and store are synonyms.. but try to use store in this cases to keep all clear. state could be confused with the state of the class.. (like `this.state`...) So here, let's use store. Also, just a detail.. we usually order first mapStateToProps (and mapDispatchToProps if there is one) and then proptypes.

2018-11-21 02:48 UTC, julibel commented on tic-tac-toe/src/app/components/game/index.js
> +          <Board squares={current.squares} onClick={i => this.props.dispatch(clickSquare(i))} />
Check all the places where this happens..

2018-11-21 19:42 UTC, jeymarsonwolox commented
- Move reducer functions to the Game class
- Organization folders to redux, screen and component.
- Creation of store.js
- Extract onClick function

2018-11-22 06:26 UTC, julibel requested changes
Great work!!! Just a few more changes and we are good to go

2018-11-22 06:26 UTC, julibel commented on tic-tac-toe/src/app/screens/game/components/board/components/square/index.js
>  function Square(props) {
for convention, if we are going to have a functions inside a function, besides the return, use class not function. In this case, you will have a class and let's use handleClick without the const.. so, if you can re use the code in the class in case you need

2018-11-22 06:26 UTC, julibel commented on tic-tac-toe/src/app/screens/game/components/board/index.js
> +import { rowItems } from '../../../../../const';
try to use indirect routes for imports (`@`).. check all the code for this 😉

2018-11-22 06:26 UTC, julibel commented on tic-tac-toe/src/app/screens/game/index.js
> +      const jumpClick = () => {
this should be outside getMoves's function. Try to keep the code as simple as you can.. a function inside a function is correct but it's a bit complex

2018-11-22 06:26 UTC, julibel commented on tic-tac-toe/src/app/screens/game/index.js
> +  history: PropTypes.arrayOf(PropTypes.any).isRequired,
It should be definde every propType... PropTypes.any will behave properly but it will lose the purpose of the PropType (that's define exactly what type of data are you expecting). Remember to use: PropTypes.shape({}), in case is an object

2018-11-22 06:26 UTC, julibel commented on tic-tac-toe/src/app/screens/game/index.js
> +const mapStateToProps = store => ({
remember to put mapStateToProp before proptypes (is a convention for order)

2018-11-22 06:26 UTC, julibel commented on tic-tac-toe/src/redux/game/reducer.js
> +const reducer = (state = initialState, action) => {
excellent work! this is exactly how a reducer looks!

2018-11-22 06:26 UTC, julibel commented on tic-tac-toe/src/redux/game/reducer.js
> +        xIsNext: action.payload.step % 2 === 0
in this case, we will leave it like this.. but, in projects, we do have files called 'utils'. There we put all functions that are likely to be used more than once and are generic. In this case, the `% 2` could be considered an operation suitable for a util (we have utils for strings, array, number, all kind of things.. always related to the project). Anyway..  this is just to know, it's not necessary to change it here 😉

2018-11-22 17:06 UTC, jeymarsonwolox commented
- Changes on PropTypes and mapStateToProps
- Changes on path of constants
- Change square component to class

2018-11-26 17:04 UTC, julibel requested changes
GREAT!! Last change! 😉

2018-11-26 17:04 UTC, julibel commented on tic-tac-toe/src/app/screens/game/index.js
> +  history: PropTypes.arrayOf(PropTypes.shape({})).isRequired,
complete proptype inside shape 😉

2018-11-26 17:26 UTC, jeymarsonwolox commented
Changes on shape of proptype.

2018-11-26 20:12 UTC, julibel approved these changes
Excellent!

2018-11-26 20:52 UTC, merged