Apply Smart & dumb pattern on Game component
wolox-training/jg-react-native pull request #7
Opened 2018-11-26 20:56 UTC by jeymarsonwolox

Summary

Apply Smart & dumb pattern on Game component

Screenshot

<img width="319" alt="captura de pantalla 2018-11-15 a la s 4 38 50 p m" src="https://user-images.githubusercontent.com/44580968/49041664-ce64d000-f193-11e8-8ebe-d996702a942f.png">

Trello card

https://trello.com/c/LP12g1LP

2018-11-26 21:57 UTC, julibel requested changes
Perfect! great start! lets use this pattern from now on in all future components and screens. Remember.. we use index and layout when the component it's complex and you will need some logic besides the minimum logic for rendering the component. In screens, we almost always have index and layout

2018-11-26 21:57 UTC, julibel commented on tic-tac-toe/src/app/screens/game/index.js
>      const history = this.props.history;
lets use destructuring here 😄

2018-11-26 21:59 UTC, julibel commented
@jeymarsonwolox one last thing
As component and screens will always be Upper case, we use folders of them with uppercase too.. can you change that?

2018-11-27 15:37 UTC, jeymarsonwolox commented
- Use of destructuring structure
- Renaming components folders.

2018-11-27 20:20 UTC, julibel approved these changes
Perfect!

2018-11-27 20:23 UTC, merged