Fea 014
wolox-training/jg-react-native pull request #9
Opened 2018-12-03 14:32 UTC by jeymarsonwolox

Summary

Partial implementation of routes, redux, redux-thunk and connected-react-router.

Screenshot

<img width="396" alt="captura de pantalla 2018-12-03 a la s 9 14 51 a m" src="https://user-images.githubusercontent.com/44580968/49379847-352b4180-f6de-11e8-8b37-5fe85a1f8a72.png">

Trello card

https://trello.com/c/zdCcKqYt

2018-12-05 03:10 UTC, julibel requested changes
Excellent! i left some comments

2018-12-05 03:10 UTC, julibel commented on tic-tac-toe/src/app/index.js
> +class App extends Component {
if you are just returning a DOM component, use function. When you are creating a new index or layour just think if you need to keep the state or if you will have more than the return function. If the answer is yes to that, then use a class, otherwise just use function. Also check eslint configuration, this should rice a warning

2018-12-05 03:10 UTC, julibel commented on tic-tac-toe/src/app/index.js
> +  history: PropTypes.object
remember that we should specify the more you can.. if this is an object, you should use `.shape({ ..here you put the definition field per field.. })`

2018-12-05 03:10 UTC, julibel commented on tic-tac-toe/src/app/screens/Login/layout.js
> +        name="username"
let's extract the name of the field to another file in the same folder call: fieldNames.js
We usually use a separate file like that.

2018-12-05 21:26 UTC, jeymarsonwolox commented on tic-tac-toe/src/app/index.js
> +  history: PropTypes.object
Correction pr #12

2018-12-05 21:33 UTC, jeymarsonwolox commented
Fieldnames correction

2018-12-05 22:24 UTC, julibel requested changes
Great.. one more change

2018-12-05 22:24 UTC, julibel commented on tic-tac-toe/src/app/screens/Login/validation/index.js
> +export const required = value => (value ? undefined : 'Value is required');
lets change this file.. we should use a utils folder in the same level that redux and inside a validations.js file 😉

2018-12-06 15:08 UTC, jeymarsonwolox commented
Change validation folder

2018-12-07 04:06 UTC, julibel approved these changes
Taking into account the other PRs where you modify a lot, specially in the actions and reducer, i think we can merge this!

2018-12-07 13:43 UTC, merged